version: 2

updates:
  - package-ecosystem: "pub"
    directory: "/'
    schedule:
      interval: "daily"
      timezone: Asia/Tokyo
      time: "06:00"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    reviewers:
      - "yuubinnkyoku"
