# NOTE: This workflow currently co-exists with the new dev-driven release process
# (prepare-release.yml + publish-release.yml). Once migration completes, consider
# disabling or removing release-please to avoid double version bumps.
name: release-please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
